version: "3.8"

services:
  mysqldb:
    build: ./mysql_db_data
    restart: unless-stopped
    ports:
      - 3306
    volumes:
      - ./mysql_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=electric_charge

  app:
    build: .
    volumes:
      - .:/code
    depends_on:
     - mysqldb
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - http_proxy=http://192.168.0.107:7890
      - https_proxy=http://192.168.0.107:7890

volumes: 
  mysql_db_data: