version: "3.8"

services:
  mysqldb:
    build: ./db-config
    restart: unless-stopped
    ports:
      - 3306
    volumes:
      - mysql_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=electric_charge

  app:
    build: .
    depends_on:
     - mysqldb
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes: 
  mysql_db_data: